### ISSUE TITLE
Connection to localhost:4584 refused

### ISSUE THREAD

**Issue by cheungaryk** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#105]
Hello, I am creating a blank issue because it doesn't seem like a bug, but rather user error (me!). I just don't know where to turn to since there aren't a lot of resources on this plugin, so here it goes. 

I am using the following:
- [Jenkins helm chart](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins) ver 3.3.9, deployed on EKS v1.16
- Jenkins version 2.277.3
- Plugin version v0.5.3
- and all other plugins are all up to date as I write this

My Jenkins pod is assuming an IAM role that has a policy in the [IAM section of the README](https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin#iam), and I tested in another pod with the same annotations/setup that it was able to assume the role and retrieve the secrets. However, as I click "test connection" in the Systems configuration page (I also triggered it using a test build), I am getting the message saying that the connection to localhost:4584 has been refused:

```bash
WARNING i.j.p.c.s.AwsCredentialsProvider#getCredentials: Could not list credentials in Secrets Manager: message=[Unable to execute HTTP request:
Connect to localhost:4584 [localhost/127.0.0.1] failed: Connection refused (Connection refused)]
```

It's my understanding that the plugin [opens this port](https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/pom.xml#L189)? However, I am not able to get any useful logs telling me where the error comes from. Would you mind giving me some tips on how to troubleshoot?

Thank you in advance.

**Comment by chriskilding** [comment]
Hi, the `localhost:4584` connection is only used for integration tests - that's the port at which Moto runs its Secrets Manager mock service.

If you were able to click the 'test connection' button, that suggests that you have a custom endpoint configuration enabled. Generally you don't need to specify the endpoint configuration - the AWS SDK figures out what the endpoint should be for almost any production installation. Could you let me know what values are present for the endpoint configuration?

**Comment by cheungaryk** [comment]
thanks for your guidance Chris, disabling the endpoint configuration works!

In retrospect, what happened is that I use JCasC and copied the code snippet directly from https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin#configuration-as-code-casc which includes the endpoint configuration block as well, so I didn't think of removing it. to avoid similar confusion, I would suggest adding an inline comment inside that code snippet reiterating that in most cases, endpoint configuration doesn't need to be specified.

**Comment by chriskilding** [comment]
Hi Gary, I've updated the CasC section in the README to present it as a schema rather than as a concrete example. I'm hoping that makes it more clear that it shouldn't simply be copy-and-pasted. Could you take a look and let me know if it does clarify it?

**Comment by cheungaryk** [comment]
yes, looks more clear now 😄 Thank you! I will close the issue now
