### ISSUE TITLE
Make cross-account usage easier

### ISSUE THREAD

**Issue by chriskilding** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#132]
Per the AWS docs it should be possible to make this plugin use Secrets Manager in a different AWS account with nothing more than standard AWS environment variables.

However some people have struggled with this, so it's not as easy as it should be.

**Comment by edhar-k** [comment]
I haven~t found for now how I can see secrets from another account. If it`s possible, could you share the docs?
By myself I tried to open access to secrets from another account and I was able to get them. But they was not listed from output of "aws secretsmanager list-secrets" and I thought that it is a reason why I can`t use secrets from another account

**Comment by chriskilding** [comment]
Here is one example of how to do it, if you're able to set profiles in ~/.aws/config: https://stackoverflow.com/a/52805686/1475135

It boils down to setting the `role_arn` in an AWS profile to the IAM role you want to assume (presumably in the other account). And then telling Jenkins to use that profile. As a result when it runs its Secrets Manager calls they *should* run against the other account.

However, at the last count, Moto - the AWS mock used to test this Jenkins plugin - does not support cross-account operations. So we can't write any automated tests in the plugin's test suite which would demonstrate this working.

**Comment by chriskilding** [comment]
Related to this, I aim to bring back a custom AWS client configuration feature in PR https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/43. This allows the STS AssumeRole strategy (among other strategies) to be configured for the plugin within Jenkins config (either in the Web UI or in CasC). This might help people who can't set these properties in the ~/.aws dotfiles.

**Comment by almiroshnich** [comment]
I also faced this problem...

Use case:
DevOps team manages shared development infrastructure inside its own AWS account.
The dedicated Jenkins controllers for other dev teams are deployed in the DevOps account inside the EKS cluster.
Each Jenkins has configured IAM roles that allow certain operations in external AWS accounts owned by the dev team.
Such _external operations_ include launching [EC2 jenkins-nodes](https://plugins.jenkins.io/ec2/) and the use of allowed resources, such as **SecretsManager**.

I've used [this guide](https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/) to configure the cross-account access to SM and can confirm that the Jenkins pod can access them
<details>
<summary>preview aws-cli</summary>

```
root@jenkins-app-646cf79db6-2ljtz:/# aws sts get-caller-identity
{
    "UserId": "CENSORED:i-987654321",
    "Account": "<ops-account>",
    "Arn": "arn:aws:sts::<ops-account>:assumed-role/jenkins-eks-role/i-987654321"
}

root@jenkins-app-XYZ:/# aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:<region>:<dev-account>:secret:sasha-cred-test-OfRs6e --region <region>
{
    "ARN": "arn:aws:secretsmanager:<region>:<dev-account>:secret:sasha-cred-test-OfRs6e",
    "Name": "sasha-cred-test",
    "VersionId": "be934e3e-fede-4da7-bf1b-9338b9546664",
    "SecretString": "cred-test",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1637185003.849
}
```

</details>

...but as reported in https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/issues/132#issuecomment-916814039 - such items aren't shown while trying to list them.

---

I was thinking if it's possible to add some options to the global plugin configuration, along with the _Endpoint Configuration_,
but [the AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/list-secrets.html) doesn't seem to support that 😢 
I wish it could be more like ECR, where the URL also includes the Id: `<registry-id>.dkr.ecr.<region>.amazonaws.com`

**Comment by almiroshnich** [comment]
A potential solution for this problem might be supporting [AWS credentials](https://plugins.jenkins.io/aws-credentials/).
_Presumable_ JCasC config:
```
credentials:
  system:
    domainCredentials:
      - credentials:
          - aws:
              id: "dev-account-access-secretsmanager"
              iamRoleArn: "arn:aws:iam::<dev-account>:role/dev-account-access-secretsmanager"
              scope: SYSTEM

unclassified:
  awsCredentialsProvider:
    endpointConfiguration:
      signingRegion: "<region>"
      credentialId: "dev-account-access-secretsmanager"
```

In this case, if Jenkins' IAM role allows assuming that external role, it would work like a charm!

**Comment by thecooldrop** [comment]
Hello I am facing this problem as well. In my case we have a Jenkins instance which is provisioned into a manager EKS cluster, which is provisioned into a separate AWS account. This Jenkins instance is then used to manage multiple clusters, and would need to access secrets from multiple AWS accounts to make them available to devs which own the clusters which are being managed by Jenkins.

Currently the plugin seems to pull only the secrets from the account to which its assumed role belongs

**Comment by chriskilding** [comment]
@thecooldrop and others - plugin v1.1.0 is now released, which allows you to specify different authentication strategies for the AWS client. One of the strategies is an IAM role. Give it a go and see if it helps.

Unfortunately you won't be able to access secrets from *multiple* accounts, but you should be able to access secrets in a *different* account to the one Jenkins runs in. That will hopefully be of use to some of you.
