### ISSUE TITLE
Unable to clone on windows due path length restriction

### ISSUE THREAD

**Issue by pravynandas** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#221]
### Jenkins and plugins versions report

<details>
  <summary>Windows</summary>

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Getting Filename too long for few files when doing repo clone

### Reproduction steps

git clone

### Expected Results

Should be able to clone

### Actual Results

Cloning into 'C:\Users\xyz\GitHub\aws-secrets-manager-credentials-provider-plugin'...
remote: Enumerating objects: 1958, done.        
remote: Counting objects: 100% (552/552), done.        
remote: Compressing objects: 100% (308/308), done.        
remote: Total 1958 (delta 245), reused 431 (delta 161), pack-reused 1406        
Receiving objects: 100% (1958/1958), 1.24 MiB | 3.37 MiB/s, done.
Resolving deltas: 100% (802/802), done.
error: unable to create file src/test/resources/io/jenkins/plugins/credentials/secretsmanager/config/migrations/ChangeFiltersToListSecretsFiltersTest/io.jenkins.plugins.credentials.secretsmanager.config.PluginConfiguration.xml: Filename too long
error: unable to create file src/test/resources/io/jenkins/plugins/credentials/secretsmanager/config/migrations/MoveEndpointConfigurationToClientTest/io.jenkins.plugins.credentials.secretsmanager.config.PluginConfiguration.xml: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by chriskilding** [comment]
1. Which Git client are you using, and how are you using it? (WSL / Cygwin / Docker / plain old Git for Windows?)
2. Which Windows version?

**Comment by chriskilding** [comment]
Looks like this is to do with the MAX_PATH limitation of 260 characters from the legacy Windows API. NTFS itself doesn't have this limit, and more Windows apps these days are Unicode-aware so they can support longer paths too.

If enabling long path support is an option for you, you could do

```
git config --system core.longpaths true
```

as described in https://stackoverflow.com/a/22575737

Then try cloning again and see what happens.

Note: depending on what other apps you're using with the codebase (e.g. your IDE or text editor), there could still be gotchas if they don't have long path support.

**Comment by chriskilding** [comment]
Did this work for you? If so I will add a note about this to the README, to help other Windows users.

**Comment by pravynandas** [comment]
nanda@DESKTOP MINGW64 ~/Github
$ git config --system core.longpaths true

nanda@DESKTOP MINGW64 ~/Github
$ git clone https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin.git
Cloning into 'aws-secrets-manager-credentials-provider-plugin'...
remote: Enumerating objects: 1958, done.
remote: Counting objects: 100% (552/552), done.
remote: Compressing objects: 100% (308/308), done.
remote: Total 1958 (delta 244), reused 432 (delta 161), pack-reused 1406
Receiving objects: 100% (1958/1958), 1.24 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (801/801), done.

Used Git bash in Admin mode, issued the git config command followed by clone, and worked like a charm. Thanks.

**Comment by pravynandas** [comment]
I got a permission denied error when ran the command in non-admin mode (because of the --global trying to edit at above user profile I guess). With Admin role it worked.

**Comment by chriskilding** [comment]
Great, could you review the change I made to the README in https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/226 and let me know if it makes sufficient sense?
