### ISSUE TITLE
when we use filters option and deploy jenkins with configuration as code, plugin is not able to read if secrets are more than 10

### ISSUE THREAD

**Issue by DeekshithSN** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#235]
### Jenkins and plugins versions report

Jenkins Version - 2.346.3
aws secret manger Plugin Version - 1.1.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

We are running jenkins as kubernetes pod using helm charts, below are chart details

repo name - https://charts.jenkins.io/
chart name - jenkins
version - 3.5.14

### Reproduction steps

      awsCredentialsProvider:
        cache: true
        listSecrets:
          filters:
            - key: name
              values:
                %{ for s in secrets ~}
                - ${s}
                %{ endfor ~}

Above is the aws secret manager plugin config used to deploy jenkins as code.
You can assume we are looping through secrets, in the above config.

when the secrets list less than 10 or 10, it works without any issue. But when we provide secrets more than 10 then jenkins is not able to read any of the secret.

When we check the logs it says

Could not list credentials in Secrets Manager: message=[1 validation error detected: Value'[secret1, secrets2....' at 'filters.1.member.values' failed to satisfy constraint: Member must have length less than or equal to 10 (Service: AWSSecretsManager; Status Code: 400; Error Code: ValidationException; Request ID: 4674747477-abccoo-2433; Proxy: null)]

In documentation also I dont see a parameter to configure number of secrets.

### Expected Results

We should have field by which we can configure number of secrets to read or all allowed secrets should be read.

### Actual Results

We should have field by which we can configure number of secrets to read or all allowed secrets should be read.

**Comment by DeekshithSN** [comment]
Any update on this team

**Comment by DeekshithSN** [comment]
Tired with standalone installation too, its same issue fails with below issue 

Could not list credentials in Secrets Manager: message=[1 validation error detected: Value '[newrelic-api-key, newrelic-api-key1, newrelic-api-key2, newreli ...' at 'filters.1.member.values' failed to satisfy constraint: Member must have length less than or equal to 10 (Service: AWSSecretsManager; Status Code: 400; Error Code: ValidationException; Request ID: a6f2f509-fd82-4881-923a-a29e05dd3784; Proxy: null)]

Jenkins Version - Jenkins 2.346.3
Aws secret manager plugin - Tried with both 1.1.0 to 1.2.0

**Comment by DeekshithSN** [comment]
actually it fails with below error 

An error occurred (ValidationException) when calling the ListSecrets operation: 1 validation error detected: Value '[newrelic-api-key, newrelic-api-key1, newrelic-api-key2, newreli ...' at 'filters.1.member.values' failed to satisfy constraint: Member must have length less than or equal to 10

**Comment by chriskilding** [comment]
Right, in that case what you are seeing is a limitation in AWS itself. You won't be able to pass this many filter criteria to it, no matter which tool you use.

If you have a group of secrets that you want to show up in Jenkins, I would recommend creating a common AWS tag on those secrets. That way you'll be able to set the tag key/value as your filter criteria in Jenkins, and only the secrets with that tag will show up in Jenkins.

Please also note that secret filters/tags are purely a client-side option to improve the user (administrator?) experience in Jenkins. They do not provide any kind of security.

**Comment by DeekshithSN** [comment]
Thank you will explore this option
