### ISSUE TITLE
Support the popular AmazonWebServicesCredentialsBinding credential types

### ISSUE THREAD

**Issue by b-sturgeon** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#296]
### What feature do you want to see added?

We manage a Jenkins instance which handles hundreds of pipelines. These pipelines often use AWS credentials from the [AWS Credentials plugin](https://plugins.jenkins.io/aws-credentials/) like the following example:
```
withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId : AWS_CREDS]]) {
    sh("make deploy_prod")  
 }
```
Or:
```
withCredentials([[$class: "AmazonWebServicesCredentialsBinding",
     accessKeyVariable: "AWS_ACCESS_KEY_ID",
     credentialsId    : FOOBAR_ACCESS_CREDS,
     secretKeyVariable: "AWS_SECRET_ACCESS_KEY"]]) {
         sh("""AWS_DEFAULT_REGION=${STACK_REGION} make promote-foobar""")
}
```

Storing these AWS credentials in AWS would make it easy to rotate them. It is likely possible to use the workarounds listed in https://plugins.jenkins.io/aws-secrets-manager-credentials-provider/#plugin-content-advanced-usage, but is not feasible for us because it would require the rewriting of hundreds of invocations in pipelines we do not own.

**Comment by cccCody** [comment]
is this the same as https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/issues/237?

**Comment by chriskilding** [comment]
Effectively yes, so I will close this as a duplicate.
