### ISSUE TITLE
The plugin does not pick up Jenkins' proxy settings

### ISSUE THREAD

**Issue by presPetkov** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#305]
### What feature do you want to see added?

Jenkins provides the users with the ability to add proxy settings.

In case that the proxy settings are set the plugin should use them for communicating with AWS.

**Comment by presPetkov** [comment]
Suggested changes https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/pull/306

**Comment by chriskilding** [comment]
Thanks for your contribution! I have left some review comments on your PR.

Would you also be able to share any details about your use case for the Jenkins proxy settings? (I've never yet had to use the proxy settings on any Jenkins setup where I've worked, so would be interested to know.)

**Comment by chriskilding** [comment]
Implemented in 1.214.va_0a_d8268d068
