### ISSUE TITLE
Allow the credential ID to be different from the underlying secret name

### ISSUE THREAD

**Issue by chriskilding** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#68]
Allow credentials to have a different ID that is different from the underlying secret's name.

For example, allow the Jenkins admin to remove a prefix from the secret name:

- When the admin specifies a credential prefix of "staging-"
- Then a secret called "staging-foo" will be shown as a credential with ID "foo"

Moved from [JENKINS-63889](https://issues.jenkins.io/browse/JENKINS-63889)

**Comment by chriskilding** [comment]
Related to #31

**Comment by chriskilding** [comment]
@hikkyXII I have reworked the 'Rename secrets' branch in #40 to bring it up to date. Would you be interested in beta testing it, to see if it meets your needs?

**Comment by hikkyXII** [comment]
Sorry, was on big vocation, missed notification. Have changed position, not managing Jenkins and AWS now.

**Comment by benh57** [comment]
Hey @chriskilding , we can try this out if you like.

**Comment by chriskilding** [comment]
@benh57 great - the experimental plugin .hpi for this feature can be found at:

https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/aws-secrets-manager-credentials-provider/1.1.1-rc180.a_2fd70c0b_c30/aws-secrets-manager-credentials-provider-1.1.1-rc180.a_2fd70c0b_c30.hpi
